language: node_js

node_js:
- '6'

addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
        
install:
- npm install

script: true

before_deploy:
- cat .netrc >> $HOME/.netrc
- chmod 0600 /home/travis/.netrc
- heroku apps
- heroku apps | grep -q ykdemo123-$TRAVIS_BRANCH || heroku apps:create ykdemo123-$TRAVIS_BRANCH
- heroku git:remote -a ykdemo123-$TRAVIS_BRANCH

deploy:
  provider: heroku
  api_key: a0301981-6cf1-42e6-baba-fd89cab0ddab
  app: ykdemo123-$TRAVIS_BRANCH
  on: $TRAVIS_BRANCH

after_deploy:
- ./node_modules/.bin/wdio wdio.conf || travis_terminate 1
